data_root : ./drive/MyDrive/AIML24/remote_sensing/otherDatasets/sentinel_2/tif
data_set : tif
train_data_path: ./drive/MyDrive/AIML24/remote_sensing/otherDatasets/sentinel_2/tif
test_data_path: ./drive/MyDrive/AIML24/testset/testset/testset
batch_size : 32
model : vit_b_16
run_id : alpha
early_stopping_patience : 5
devices : 3
learning_rate : 0.0001
max_epochs : 1000 # Lightning default
valid_size : 2700
num_nodes : 1
