data_root : ../drive/MyDrive/AIML24/remote_sensing/otherDatasets/sentinel_2
data_set : tif
batch_size : 128
model : vit_b_16
run_id : eurosat_alpha
early_stopping_patience : 5
devices : 1
learning_rate : 0.0001
